- BrightID/src/components/OnboardingScreens/Onboard.js
Upon installation and startup, the onboard slider only has two pages with content and then has two blank pages. I removed the blank ones.
> remove unused onboard entries

- BrightID/src/Api/BrightId.js
- BrightID/src/actions/fetchUserInfo.js
- BrightID/src/actions/index.js
- BrightID/src/components/GroupsScreens/EmptyGroups.js
- BrightID/src/components/GroupsScreens/NewGroupCard.js
- BrightID/src/components/GroupsScreens/actions.js
- BrightID/src/reducer/index.js
- BrightID/src/reducer/main.js
- BrightID/src/utils/encoding.js
- BrightID/src/utils/groups.js
After upgrading to BrightID-Node v3.0.0, as creating group requests will be applied to the database with a delay, we can not rely on the data that we query from the server, for listing the eligible groups in the groups' tab. Currently, users can not see the groups after founding them on the groups' screen and think that there is a problem there.
To solve this issue, we should add the newly founded groups to the local redux storage and rely on this local data instead of remote data for showing groups just like what we have for connections.
This is what is implemented in this branch.
> store groups information locally

- BrightID/src/actions/fakeContact.js
- BrightID/src/actions/fetchUserInfo.js
- BrightID/src/actions/index.js
- BrightID/src/components/Connections/ConnectionCard.js
- BrightID/src/components/NewConnectionsScreens/actions/addNewConnection.js
- BrightID/src/reducer/index.js
After upgrading to BrightID-Node v3.0.0, the connections can be in 3 different states, initiated and waiting for confirmation, confirmed and deleted. So we should update local connections data every time we query the connections and show in the connections screen. It includes issue #251.
> resolved #251, show the connections' status

- BrightID/src/components/GroupsScreens/GroupsScreen.js
- BrightID/src/components/GroupsScreens/SearchGroups.js
- BrightID/src/utils/groups.js
Extend group filter to take member names into account.
When you enter a search string it will now match against the group name and group members.
This should fix #273.
> feat: Filter groups by name of user in group

- BrightID/src/components/GroupsScreens/GroupsScreen.js
- BrightID/src/components/GroupsScreens/models/sortingUtility.js
- BrightID/src/reducer/groups.js
This should fix #372. Groups are now sorted only based on joinDate, starting with most recently joined group.
@RnbWd I moved the sorting logic from redux store to the UI layer as we had shortly discussed. Let me know if this looks good for you!
> Sort Groups Tab by most recent by default

- BrightID/src/components/Apps/model.js
Linking to apps is broken.  Something must have been decoding urls automatically and an upgrade changed that behavior.
@RnbWd This hotfix should be released to app stores immediately.
Feel free to bump versions in this hotfix branch or in master after it's merged.
> Linking to apps is broken

- BrightID/src/components/GroupsScreens/NoGroups.js
Should fix #277
I don't think there is need to go through emitter, so I replaced it with Linking.openURL.
> fix: learn more button now opens url

- BrightID/src/components/Apps/AppCard.js
- BrightID/src/reducer/apps.js
Should fix #427
If you try to link to an contextID that is already used by another BrightID you will now get the backend error message displayed:
> feat: show backend error message when linking fails

- BrightID/src/Api/BrightId.js
- BrightID/src/App.js
- BrightID/src/components/Connections/ConnectionCard.js
- BrightID/src/components/Connections/ConnectionsScreen.js
- BrightID/src/components/NewConnectionsScreens/actions/addNewConnection.js
- BrightID/src/components/NewConnectionsScreens/actions/profile.js
- BrightID/src/utils/constants.js
- BrightID/src/utils/cryptoHelper.js
- BrightID/src/utils/operations.js
Changes:
- Don't show flag button for connections in waiting state
- Track 'Add Connection' operation also on the responder side (the person that scanned other persons code). This makes the connection change automatically from 'waiting' to 'connected'. 
- If a connection is in waiting state for more than 1 minute mark it as stale:
- update the connection label to "Connection failed. Please try again".
- add an 'X' button to the connection that enables to remove the stale connection (after confirmation)
- If a connection is in "deleted" state (you have been flagged by the other person), also show the 'X' button instead of the flag button, so you can remove the deleted connection
This should fix #364 and partly deals with #311.
> Handle waiting and deleted connections

- BrightID/src/api/channelService.js
- BrightID/src/api/channelService.test.js
- BrightID/src/components/NewConnectionsScreens/actions/channelThunks.js
- BrightID/src/utils/constants.js
If creating new or joining existing channel fails (e.g. because profile upload failed):
- show an Alert to the user with error message
- dispatch(leaveChannel) to have a consistent state
> Handle channel errors

- BrightID/src/components/SideMenu/GraphExplorerScreen.js
When you click on the explorer link it opens an alert instead of opening the device browser to show the explorer. 
This should fix that, My Apologies if there's an issue with syntax or if the implementation could be better, I've never worked with React 😄
> (Patch) Opening Explorer Link 

- BrightID/src/components/Connections/ConnectionsScreen.js
- BrightID/src/components/GroupsScreens/GroupsScreen.js
- BrightID/src/components/GroupsScreens/NewGroups/NewGroupScreen.js
- BrightID/src/utils/strings.js
As requested in issue #519 , this makes searches accent insensitive.
Before :
- Connections searches were case and space insensitive.
- Groups and Group Member searches were case insensitive.
With this PR : All types of search (connection, group, group member) are case, space and accent insensitive.
On the performance side, it is adding extra string RegExp execution on-top of what was done before. 
Note that on the Connections page those RegExp are executed regardless of if there is a search ongoing or not (as opposed to the Groups page), so there is an easy optimization possible there if you are OK with it.
> [f/519] Accent/Case/Space Insensitive Searches

- BrightID/src/components/PendingConnectionsScreens/actions/channelThunks.js
Currently we keep polling for profiles until a channel gets closed, even if no more profiles are expected.
This change immediately stops polling when the expected number of profiles (depending on channel type) is found.
This should help reduce data usage and system load both on client side and profile server.
> Stop polling for profiles when expected number of profiles is found

- BrightID/android/app/build.gradle
Required to make codePush updates targeting a version range possible.
> Remove versionNameSuffix from Android Staging build

- BrightID/e2e/i18n_for_tests.js
- BrightID/e2e/onboarding.spec.js
- BrightID/e2e/testUtils.js
- BrightID/src/components/OnboardingScreens/Eula.js
- BrightID/src/components/PendingConnectionsScreens/PreviewConnectionController.js
Fixes really stupid code where I was returning a dummy pendingConnection object when the pendingConnection was not existing. This resulted in the app crashing whenever a channel expired while the UI showing the pending connection previews.
Also included detox updates to handle new EULA screen and changed location of translation files.
> Fix expiring channel

- BrightID/src/App.js
- BrightID/src/components/Apps/AppCard.js
Fixes 2 potential causes for the crashes we are seeing reported in appcenter (`Unhandled JS Exception: Invariant Violation: Invalid URL: should be a string. Was: undefined`).
> Potential fix for undefined url crash

- BrightID/flow-typed/myLibDef.js
- BrightID/src/api/brightId.js
- BrightID/src/api/channelService.js
- BrightID/src/components/PendingConnectionsScreens/QrCode.js
- BrightID/src/components/PendingConnectionsScreens/ScanCodeScreen.js
- BrightID/src/components/PendingConnectionsScreens/actions/channelThunks.js
- BrightID/src/components/PendingConnectionsScreens/channelSlice.js
- BrightID/src/components/Recovery/thunks/channelThunks.js
- BrightID/src/components/Recovery/thunks/recovery.test.js
- BrightID/src/utils/channels.js
- BrightID/src/utils/channels.test.js
- BrightID/src/utils/constants.js
Remove the existing fallback logic for old-style qrcodes.
Also remove the `ip()` method from node API as it is not used anymore.
> Remove qrcode fallback

- BrightID/locales/en/translation.json
This PR changes english strings. Updates for other languages will have to come in via weblate.
Fixes #703
> Always refer to recovery connections as "recovery," not "trusted"

- BrightID/src/components/Onboarding/RecoveryFlow/RecoveringConnectionCard.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/RecoveringConnectionScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/RecoveryCodeScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/TrustedConnectionsScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/recoveryDataSlice.ts
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/channelThunks.ts
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/recovery.test.ts
- BrightID/src/components/PendingConnections/ScanCodeScreen.tsx
- BrightID/src/utils/constants.ts
- BrightID/src/utils/recovery.ts
- BrightID/types.d.ts
QRCodes for recovery are now created similar to connection codes. So the creator of the code includes the url to the profile server for data exchange. The people scanning the code will use that url instead of default `node.brightid.org`.
Fixes #777
> Include profile server url in recovery qrcode

- BrightID/e2e/testUtils.js
I tried to test the app with the steps that are mentioned in the wiki. However, when the mock client changes to photo in the submit photo page, it tries to tap the "submitPhoto" button immediately, which is disabled and takes some time to get enabled
I tried to find a solution to wait for the button to get enabled but it's still an issue in detox that doesn't have a solution:
https://github.com/wix/detox/issues/246
So, I used a 2-second sleep to wait for the button to get enabled. And now, tests are working.
> wait for submit photo button to be enabled in tests

- BrightID/android/app/build.gradle
- BrightID/locales/de/translation.json
- BrightID/locales/en/translation.json
- BrightID/locales/es/translation.json
- BrightID/locales/fa/translation.json
- BrightID/locales/fr/translation.json
- BrightID/locales/hi/translation.json
- BrightID/locales/ru/translation.json
- BrightID/locales/zh_Hans/translation.json
- BrightID/locales/zh_Hant/translation.json
- BrightID/src/components/Connections/ConnectionScreen.tsx
- BrightID/src/utils/constants.ts
- BrightID/src/utils/stringSimilarity.ts
I used a string similarity code to figure out if a connection's name is similar to another one and showing possible duplicates of one connection in it's details page. 
https://github.com/BrightID/BrightID/issues/61#issuecomment-679317422
> add possible duplicates of a connection to connection details screen

- BrightID/e2e/reconnect.spec.ts
- BrightID/src/actions/fakeContact.ts
- BrightID/src/api/response_types.d.ts
- BrightID/src/components/Notifications/PendingConnectionCard.tsx
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelUploadThunks.ts
- BrightID/src/components/PendingConnections/GroupConnectionScreen.tsx
- BrightID/src/components/PendingConnections/PendingConnectionsScreen.tsx
- BrightID/src/components/PendingConnections/PreviewConnectionController.tsx
- BrightID/src/components/PendingConnections/PreviewConnectionView.tsx
- BrightID/src/components/PendingConnections/ReconnectView.tsx
- BrightID/src/components/PendingConnections/actions/channelThunks.ts
- BrightID/src/components/PendingConnections/actions/pendingConnectionThunks.ts
- BrightID/src/components/PendingConnections/pendingConnectionSlice.ts
- BrightID/types.d.ts
Improve code maintanability by splitting the huge pendingConnection object/type, to have a better view which information is obtained from where.
> Refactor pending connections

- BrightID/e2e/importAccount.spec.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelDownloadThunks.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelThunks.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelUploadThunks.ts
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/recovery.test_disabled.ts
- BrightID/src/utils/channels.ts
- BrightID/types.d.ts
fixes #966
This only takes care of v5 linked contexts, not apps using v6 blind signatures.
> Sync linked apps when importing BrightID to another device.

- BrightID/src/api/brightId.ts
- BrightID/src/api/operation_types.d.ts
- BrightID/src/reducer/operationsSlice.ts
- BrightID/src/utils/operations.ts
Changes:
- Reduce duplicate code in brightID api by adding `submitOp` function
- Add `postTimestamp` to all operations and set it to the timestamp when operation gets submitted to node api
- Always use postTimestamp when dealing with trace time
Fixes #993
> Always use `postTimestamp` property for deciding if an operation is expired.

- BrightID/src/components/Connections/ConnectionScreen.tsx
- BrightID/src/components/Connections/ConnectionScreenController.tsx
- BrightID/src/utils/constants.ts
Move duplicate detection code into ConnectionController.
Reduce system load by ignoring duplicates when number of connections is very high.
Refactor update of connection verifications.
> refactor connection screen

- BrightID/locales/en/translation.json
- BrightID/src/api/brightId.ts
- BrightID/src/api/response_types.d.ts
- BrightID/src/components/Apps/AppsScreen.tsx
- BrightID/src/components/Apps/model.ts
- BrightID/src/reducer/userSlice.ts
- Prevents sponsorship for v6 and soulbound apps if the `appUserId` is used by another user to get sponsored before. This prevents apps to use sponsored `appUserId`s of other apps for not sponsored users to bypass the sponsorship system.
- Enables v5 soulbound apps to use the v6 sponsorship model.
> enable soulbound apps to use v6 sponsorship model

- BrightID/locales/en/translation.json
- BrightID/src/actions/apps.ts
- BrightID/src/components/Apps/AppsScreen.tsx
- BrightID/src/components/Apps/AppsScreenController.tsx
- BrightID/src/components/Apps/model.ts
- BrightID/src/components/HomeScreen.tsx
- BrightID/src/reducer/appsSlice.ts
- Prevent multiple concurrent calls of `updateBlindSigs` by using `useEffect` instead of `useFocusEffect` to trigger its call
- Prevents single app `updateBlindSig` for a single app on linking to run simultaneously by global `updateBlindSigs`
- Updates apps info before linking to ensure recent changes to the app settings are being used
- Ignores trying to link invalid signature objects
> fix bugs in updating blind sigs

- .github/workflows/build_android.yml
- .github/workflows/build_iOS.yml.disabled
- .github/workflows/unittest.yml
we still are using node 12.x which is being deprecated on github.
> Switch github actions to node.js 16.x

- BrightID/src/App.tsx
- BrightID/src/bootstrap.ts
- BrightID/src/components/Helpers/InitialLoadingScreen.tsx
- BrightID/src/components/HomeScreen.tsx
- BrightID/src/components/Onboarding/ImportFlow/ImportScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/RecoveryCodeScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/RestoreScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/channelThunks.ts
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/recoveryThunks.ts
- BrightID/src/reducer/keypairSlice.ts
- BrightID/src/routes/MissingKeysScreen.tsx
- BrightID/src/routes/index.tsx
- BrightID/src/utils/constants.ts
- BrightID/src/utils/cryptoHelper.test.ts
- BrightID/src/utils/cryptoHelper.ts
- BrightID/src/utils/encoding.ts
Implement various changes to prevent invalid/missing secret key issues:
- At app startup check for valid keypair. If the keypair is invalid, show according screen and prevent any usage of app
- When performing recovery, check if a valid keypair is set. If the keypair is not valid, show an error and abort the recovery process
- When importing BrightID from another device, check if a valid keypair is set. If the keypair is not valid, show an error and abort the import process
- Fix potential race condition in app startup process
> Check secret key

- BrightID/locales/en/translation.json
- BrightID/src/components/Onboarding/ImportFlow/AddDeviceScreen.tsx
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelUploadThunks.ts
- BrightID/src/components/PendingConnections/ScanCodeScreen.tsx
- BrightID/src/utils/constants.ts
We're adding this to be able to login to Aura with the import feature from BrightID.
Current import functionality imports every data, including connections which we don't need in Aura. So I added an import type to work for this purpose and only import basic user info
You can use this frontend to test the feature:
https://aura-frontend-git-brightid-superapp-import-brightid.vercel.app/
> feat: add ADD_SUPER_USER_APP import type

- BrightID/e2e/connectionDetails.spec.ts
- BrightID/e2e/reconnect.spec.ts
- BrightID/e2e/testUtils.ts
- BrightID/locales/en/translation.json
- BrightID/src/actions/fakeContact.ts
- BrightID/src/components/Connections/TrustLevelView.tsx
- BrightID/src/components/Connections/TrustlevelSlider.tsx
- BrightID/src/components/Helpers/ConnectionStatus.tsx
- BrightID/src/components/PendingConnections/RatingView.tsx
- BrightID/src/utils/connectionLevelStrings.ts
- BrightID/src/utils/connectionTestButton.tsx
We might need to define some custom levels for when an Aura player is evaluating a BrightID user which is not necessarily a BrightID connection of that Aura player.
This pull request is to make sure that the UI does not break with these unknown connection levels.
> refactor: handle unknown connection levels

- BrightID/src/components/Connections/ConnectionCard.tsx
- BrightID/src/components/Connections/models/reportConnection.ts
- BrightID/src/components/Groups/actions.ts
- BrightID/src/components/Notifications/InviteCard.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/backupThunks.ts
- BrightID/src/components/PendingConnections/PendingConnectionsScreen.tsx
- BrightID/src/components/PendingConnections/actions/pendingConnectionThunks.ts
- BrightID/src/reducer/connectionsSlice.ts
Currently if a user uses multiple devices to make connections, the device that is used later will override the backup data and does not load the current backup data related to the connections made by their other device. I created this PR to make sure that multiple devices stay in sync with the backup service while creating connections
> feat: pull connection backup data before uploading
