- BrightID-rn/AppRoutes.js
- BrightID-rn/components/Onboard.js
- BrightID-rn/components/SignUp.js
- BrightID-rn/components/onboardingScreens/MaintainPrivacy.js
- BrightID-rn/containers/SignUp.js
> Signup Screen UI

- BrightID-rn/package.json
- BrightID-rn/src/AppBootstrap.js
- BrightID-rn/src/actions/index.js
- BrightID-rn/src/store/index.js
Hi @RnbWd Here's what I have so far. I haven't yet completed the work on signing and exchanging the key. Just want you to look at my use of redux and location of functions etc.
> !!Dont Merge Yet!!! - Setting up Public Private Key exchange on startup

- BrightID/src/components/HomeScreen.js
- BrightID/src/components/NewConnectionsScreens/ScanCodeScreen.js
- BrightID/src/components/NewConnectionsScreens/actions/fetchData.js
- BrightID/src/components/NewConnectionsScreens/actions/parseQrData.js
- BrightID/src/components/NewConnectionsScreens/actions/websocket.js
The ScanCodeScreen has a TextInput that listens for any change in text. When the text changes, the application immediately sends a web request (even if just one character is typed). The BrightID application then tries to perform a substring without validating the length.
This PR checks if the length is appropriate before attempting to send the QR URI to BrightID-Node.
I also had some weird behavior regarding the layouts moving when the keyboard focused. I added a z-index to make sure the camera view does not cover the text input field.
I also encountered some commented out code, prettier issues, and fixed them as I went.
This resolves #226
> Allow Manual Typing of QR Code

- BrightID/src/components/GroupsScreens/Members/InviteListScreen.js
- BrightID/src/components/GroupsScreens/Members/MemberCard.js
- BrightID/src/components/GroupsScreens/Members/MembersScreen.js
- BrightID/src/components/NewConnectionsScreens/PreviewConnectionScreen.js
- BrightID/src/reducer/index.js
> merge flagging into dev

- BrightID/src/Api/BrightId.js
- BrightID/src/actions/apps.js
- BrightID/src/actions/index.js
- BrightID/src/actions/operations.js
- BrightID/src/components/Apps/AppCard.js
- BrightID/src/components/Apps/model.js
- BrightID/src/reducer/apps.js
- BrightID/src/reducer/operations.js
- BrightID/src/utils/operations.js
> Issue #281

- BrightID/e2e/addConnections.spec.js
- BrightID/e2e/groups.spec.js
- BrightID/e2e/testUtils.js
- BrightID/src/components/Connections/ConnectionsScreen.js
- BrightID/src/components/Connections/models/sortingUtility.js
- BrightID/src/components/NewConnectionsScreens/SuccessScreen.js
Also fixes bug in connection sorting :)
Closes #348
> Open connections screen with newest connection first after making a connection 

- BrightID/src/components/GroupsScreens/Members/MembersScreen.js
> fix: removed group members are note removed from UI

- BrightID/flow-typed/myLibDef.js
- BrightID/src/Api/BrightId.js
- BrightID/src/actions/groups.js
- BrightID/src/components/GroupsScreens/Members/MemberCard.js
- BrightID/src/components/GroupsScreens/Members/MembersScreen.js
- BrightID/src/reducer/groups.js
> feat: Enable group admin to make other members admin

- BrightID/src/components/Notifications/InviteCard.js
- BrightID/src/components/Notifications/NotificationsScreen.js
- BrightID/src/reducer/groups.js
Fixes #420 and state mutation error in groups reducer.
> navigate to groups screen after joining group

- BrightID/src/components/NewConnectionsScreens/ScanCodeScreen.js
- BrightID/src/components/NewConnectionsScreens/actions/channelThunks.js
- BrightID/src/components/NewConnectionsScreens/channelSlice.js
- BrightID/src/components/NewConnectionsScreens/pendingConnectionSlice.js
- BrightID/src/routes/Home.js
refactor ScanCodeScreen to prevent joining the same channel multiple times.
> fix: prevent joining channel multiple times

- BrightID/src/actions/fakeContact.js
- BrightID/src/components/Helpers/NotificationBanner.js
- BrightID/src/components/PendingConnectionsScreens/MyCodeScreen.js
- BrightID/src/components/PendingConnectionsScreens/PendingConnectionsScreen.js
- BrightID/src/components/PendingConnectionsScreens/QrCode.js
- BrightID/src/components/PendingConnectionsScreens/ScanCodeScreen.js
- BrightID/src/components/PendingConnectionsScreens/pendingConnectionSlice.js
- BrightID/src/routes/PendingConnections.js
- BrightID/src/routes/index.js
Refactored QRCode Component
Added Pending Connection Button and Title for group connections
> update group connection ui

- BrightID/src/components/GroupsScreens/Members/MemberCard.js
Change conditional rendering to prevent React error about Text not being rendered inside View.
> Fix: React rendering error when checking user flagged state

- BrightID/src/bootstrap.js
- BrightID/src/components/Tasks/TaskCard.js
- BrightID/src/components/Tasks/TaskState.js
- BrightID/src/components/Tasks/TasksProgress.js
- BrightID/src/components/Tasks/TasksScreen.js
- BrightID/src/components/Tasks/TasksSlice.js
> Tasks updates

- BrightID/src/components/Connections/ConnectionCard.js
- BrightID/src/components/Connections/SortingConnectionsScreen.js
- BrightID/src/components/Connections/models/sortingUtility.js
- BrightID/src/components/GroupsScreens/Members/MemberCard.js
- BrightID/src/components/GroupsScreens/Members/MembersScreen.js
- BrightID/src/components/GroupsScreens/NewGroups/NewGroupCard.js
- BrightID/src/components/GroupsScreens/NoGroups.js
- BrightID/src/components/Recovery/TrustedConnectionCard.js
Remove all mentions of score from the UI.
Fixes #359
> Remove scores

- BrightID/src/api/brightId.js
- BrightID/src/components/GroupsScreens/Members/MembersScreen.js
> fix: leave group works again

- BrightID/src/api/brightId.js
> fix addAdmin method missing

- BrightID/package.json
- BrightID/src/components/HomeScreen.js
version info is read from package.json, so this needs to be updated when preparing a release.
fixes #535
> feat: show version info in app

- BrightID/src/api/brightId.js
- BrightID/src/components/Recovery/BackupScreen.js
Looks like this bug got introduced with the apiv5 changes.
> fix: recovery not working

- BrightID/src/components/PendingConnectionsScreens/QrCode.js
Starting with that issue to get familiar with the code and see how to contribute.
On a side note, I don't see any mention of internationalization in the backlog. Is supporting multiple languages something you'd like to keep for later or would you be interested if I'd look at it ?
> [issues/526] Different text for single/group links

- BrightID/src/components/Connections/ConnectionCard.js
> feat: show verification status in connection list

- BrightID/src/reducer/connections.js
- BrightID/src/utils/operations.js
Changes:
- Don't dispatch(fetchUserInfo()) repeatedly.
- Enable connections to change from "deleted" to "verified" again.
fixes #590
> Connections appearing as deleted

- BrightID/e2e/makeConnections.spec.js
- BrightID/e2e/reconnect.spec.js
- BrightID/flow-typed/myLibDef.js
- BrightID/src/actions/fakeContact.js
- BrightID/src/components/Connections/ConnectionScreenController.js
- BrightID/src/components/Connections/ConnectionsScreen.js
- BrightID/src/components/Connections/TrustLevelView.js
- BrightID/src/components/Connections/models/flagConnection.js
- BrightID/src/components/Helpers/EmptyList.js
- BrightID/src/components/PendingConnectionsScreens/ConnectionStats.js
- BrightID/src/components/PendingConnectionsScreens/PendingConnectionsScreen.js
- BrightID/src/components/PendingConnectionsScreens/PreviewConnectionController.js
- BrightID/src/components/PendingConnectionsScreens/PreviewConnectionView.js
- BrightID/src/components/PendingConnectionsScreens/ProfileCard.js
- BrightID/src/components/PendingConnectionsScreens/RatingButton.js
- BrightID/src/components/PendingConnectionsScreens/RatingView.js
- BrightID/src/components/PendingConnectionsScreens/ReconnectView.js
- BrightID/src/utils/connectionLevelStrings.js
- BrightID/src/utils/fakeHelper.js
Implement reconnect screen + E2E tests.
> Bright id 582

- BrightID/e2e/reconnect.spec.js
- BrightID/e2e/testUtils.js
- BrightID/src/actions/fakeContact.js
- BrightID/src/components/Connections/ConnectionScreenController.js
- BrightID/src/components/Connections/ConnectionsScreen.js
- BrightID/src/components/Connections/models/flagConnection.js
- BrightID/src/components/PendingConnectionsScreens/ProfileCard.js
- BrightID/src/components/PendingConnectionsScreens/ReconnectView.js
Just show profile and "reconnect" button when reconnecting with identical profile.
Fixes #601.
> Reconnect same profile

- BrightID/ios/BrightID/BrightID.entitlements
- BrightID/src/NavigationService.js
- BrightID/src/components/EditProfile/EditProfileScreen.js
- BrightID/src/components/EditProfile/SelectSocialMediaModal.js
- BrightID/src/components/Recovery/BackupScreen.js
- BrightID/src/routes/Home.js
- BrightID/src/routes/HomeDrawer.js
updated ios password handling,
updated how data is saved in editProfile
> Edit name ios password

- BrightID/src/actions/fakeContact.js
- BrightID/src/components/PendingConnectionsScreens/actions/channelThunks.js
- BrightID/src/components/PendingConnectionsScreens/pendingConnectionSlice.js
- BrightID/src/utils/constants.js
Quick solution to notify user when trying to connect with incompatible client version.
It is not a perfect solution:
- If you receive many outdated profiles the Alerts will only stack partly, so you will not see all affected users.
- Triggering the Alert() directly within `fetchChannelProfiles` thunk is not nice. But we don't have a general Alert component integrated with Redux, so for now that's the best low-effort solution.
> Alert on incompatible profile version

- BrightID/e2e/connectionList.spec.js
- BrightID/src/components/Connections/ConnectionCard.js
> Show connection level in connection list

- BrightID/src/components/Connections/ConnectionCard.js
- BrightID/src/components/Connections/ConnectionScreen.js
- BrightID/src/components/GroupsScreens/Members/MemberCard.js
- BrightID/src/components/PendingConnectionsScreens/PreviewConnectionView.js
- BrightID/src/utils/connectionLevelStrings.js
> Use report term instead of flag in the client

- BrightID/locales/de/translation.json
- BrightID/locales/en/translation.json
- BrightID/locales/es/translation.json
- BrightID/locales/fr/translation.json
- BrightID/src/components/Notifications/InviteCard.js
- BrightID/src/routes/Connections.js
- BrightID/src/routes/Groups.js
This adds some missing translation keys and should help in aligning code style of translation files generated locally (by running i18next) and generated by weblate.
> Fix translations

- BrightID/e2e/apps.spec.js
Add missing apps, some refactoring of testspec.
> update detox tests for app linking

- BrightID/e2e/reconnect.spec.js
- BrightID/locales/en/translation.json
- BrightID/src/components/Connections/TrustlevelModal.js
- BrightID/src/components/Connections/TrustlevelSlider.js
- BrightID/src/components/PendingConnectionsScreens/PendingConnectionsScreen.js
- BrightID/src/components/PendingConnectionsScreens/ReconnectView.js
> Enable change of connection level on reconnect screen

- BrightID/i18n.js
> Activate Hindi language in client

- BrightID/src/components/Onboarding/RecoveryFlow/RecoverAccount.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/RecoveringConnectionScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/channelDownloadThunks.ts
> Show all connections as account recovery candidates

- BrightID/src/components/PendingConnections/ReconnectView.tsx
> Fix: Add missing incomingLevel to TrustlevelSlider when reconnecting

- BrightID/src/components/Notifications/InviteCard.tsx
- BrightID/src/components/Notifications/NotificationsScreen.tsx
- BrightID/src/reducer/groupsSlice.ts
- BrightID/src/utils/invites.js
A bunch of fixes for accepting/rejecting group invites.
> Fix group invite/reject

- BrightID/src/components/EditProfile/EditProfileScreen.tsx
> Always show explanation about how password is used in profile screen

- BrightID/src/components/Connections/ConnectionCard.tsx
> Fix: Update backup in case a connection got removed.

- BrightID/src/api/response_types.d.ts
- BrightID/src/api/verification_types.d.ts
- BrightID/src/components/Tasks/UserTasks.ts
- BrightID/src/reducer/userSlice.ts
- BrightID/types.d.ts
> Fix achievement "Join Connection party"

- BrightID/src/components/Tasks/UserTasks.ts
Fix "Joined connection party" achievement.
> Fix: Add missing return statement in task check function

- BrightID/locales/en/translation.json
- BrightID/src/components/PendingConnections/PreviewConnectionView.tsx
- BrightID/src/components/PendingConnections/ProfileCard.tsx
- BrightID/src/components/PendingConnections/ReconnectView.tsx
- BrightID/types.d.ts
display if connection is `reported` when reconnecting
if a user reported them, always display `reported` and the `reason` from the user
> show user reported and reconnect reported

- BrightID/locales/en/translation.json
- BrightID/src/components/PendingConnections/PreviewConnectionView.tsx
- BrightID/src/components/PendingConnections/ProfileCard.tsx
Update Pending connection to show when user's connected and display reporting better
> Add created date

- BrightID/ios/BrightID.xcodeproj/project.pbxproj
- BrightID/package.json
- BrightID/src/api/response_types.d.ts
- BrightID/src/components/Apps/AppCard.tsx
filter apps that are in testing - do not display them unless linked
> Filter test apps

- .github/workflows/build_android.yml
- BrightID/android/app/build.gradle
- BrightID/android/build.gradle
- BrightID/android/gradle.properties
This should fix automated builds via github actions. See #886 for more details on the root cause.
> Pin NDK version to 22.1.7171670

- BrightID/android/app/src/main/res/values/colors.xml
- BrightID/android/app/src/main/res/values/styles.xml
> Set default black text color (Android)

- BrightID/locales/en/translation.json
- BrightID/src/actions/apps.ts
- BrightID/src/api/brightId.ts
- BrightID/src/api/brightidError.ts
- BrightID/src/api/operation_types.d.ts
- BrightID/src/api/response_types.d.ts
- BrightID/src/components/Apps/AppsScreen.tsx
- BrightID/src/components/Apps/model.ts
- BrightID/src/reducer/appsSlice.ts
- BrightID/types.d.ts
Add sponsoring for new v6 workflow
> V6 sponsor

- BrightID/locales/en/translation.json
- BrightID/src/components/Onboarding/RecoveryFlow/RestoreBackup.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/RestoreScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/recoveryThunks.ts
> Show progress while restoring backup

- BrightID/package.json
- BrightID/src/actions/notifications.ts
- BrightID/src/utils/invites.js
Contains a possible fix for app crashing when clicking on notification icon
> Prepare next release

- BrightID/e2e/importAccount.spec.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelDownloadThunks.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelThunks.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelUploadThunks.ts
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/channelUploadThunks.ts
- BrightID/src/reducer/settingsSlice.ts
- BrightID/src/utils/channels.ts
- BrightID/src/utils/constants.ts
Make use of the existing prefix 'sig_' to not hit the channel limit.
> add prefix to uploaded data to prevent triggering channel limit

- BrightID/locales/en/translation.json
- BrightID/src/components/Onboarding/RecoveryFlow/RecoveryCodeScreen.tsx
fixes #969 Wrong message when copying qrcode for importing a device
> Don't use 'recovery' strings when importing/syncing

- BrightID/locales/en/translation.json
- BrightID/src/components/HomeScreen.tsx
- Checks if the user's public key is in server-side signing keys on initialization
> check signing key

- .github/workflows/codepush.yml
Automatically create a (disabled) Staging release in appcenter codepush whenever master branch is pushed.
> Automate staging deploy

- .github/workflows/codepush.yml
Automatically create a (disabled) Staging release in appcenter codepush whenever master branch is pushed.
> Automate staging deploy (#989)

- .github/workflows/build_android.yml
> Build Android Release aab from github action

- BrightID/e2e/importAccount.spec.ts
- BrightID/src/components/Apps/AppsScreen.tsx
- BrightID/src/components/Apps/model.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelDownloadThunks.ts
- BrightID/src/components/Onboarding/ImportFlow/thunks/channelUploadThunks.ts
- BrightID/src/components/Tasks/UserTasks.ts
- BrightID/src/reducer/types.d.ts
- BrightID/src/reducer/userSlice.ts
> Separate tracking of v5 (server-side) and v6 (client-side) sponsoring.

- BrightID/e2e/groupManagement.spec.ts
- BrightID/locales/en/translation.json
- BrightID/src/components/Groups/GroupCard.tsx
- BrightID/src/components/Groups/Members/MembersScreen.tsx
> Bright id 836

- BrightID/src/components/Apps/model.ts
- BrightID/src/components/Onboarding/ImportFlow/DevicesScreen.tsx
- Indicate on devices screen if the current device is "primary" or "secondary"
- Prevent linking with v6 app on a secondary device if the blind sig is missing and inform user
Fixes #1016
> Improve app linking on secondary devices

- BrightID/.eslintrc.js
- BrightID/e2e/findFriends.spec.ts
- BrightID/e2e/testUtils.ts
- BrightID/package.json
- BrightID/src/api/socialMediaService.ts
- BrightID/src/components/EditProfile/socialMediaThunks.test.ts
- BrightID/src/components/EditProfile/socialMediaThunks.ts
- BrightID/src/components/FindFriends/FindFriendsScreen.tsx
- BrightID/src/reducer/socialMediaSlice.ts
- BrightID/src/routes/HomeDrawer.tsx
- BrightID/src/utils/ContactsProvider.e2e.ts
- BrightID/src/utils/ContactsProvider.ts
- BrightID/src/utils/socialMediaServiceProvider.e2e.ts
- BrightID/src/utils/socialMediaServiceProvider.ts
- BrightID/yarn.lock
Add basic detox tests for FindFriends screen.
Uses mock implementation for Contacts access and SocialMediaService.
> Find friends e2e

- BrightID/src/components/Apps/AppsScreen.tsx
- BrightID/src/components/Apps/AppsScreenController.tsx
- BrightID/src/components/Apps/AppsScreenFilter.tsx
- BrightID/src/routes/Apps.tsx
Split code into smaller components and few cleanups, fix problem of keyboard disappearing when entering a character
> improve Appsscreen

- BrightID/src/components/Apps/model.ts
- Prevents getting errors on spending sponsorship and failing to link if user is already sponsored
> prevent getting error if sponsorship already spent

- BrightID/package.json
- BrightID/src/components/EditProfile/EditProfileScreen.tsx
- BrightID/src/components/EditProfile/SelectSocialMediaModal.tsx
- BrightID/src/components/EditProfile/socialMediaThunks.ts
- BrightID/src/reducer/settingsSlice.ts
- BrightID/src/reducer/socialMediaSlice.ts
- BrightID/src/utils/constants.ts
- BrightID/src/utils/socialUtils.ts
- BrightID/types.d.ts
- BrightID/yarn.lock
> Social media share

- BrightID/src/routes/Devices.tsx
> Use translated string for "devices"

- BrightID/jestSetupFile.ts
- BrightID/src/actions/fetchUserInfo.ts
- BrightID/src/api/verification_types.d.ts
- BrightID/src/components/Apps/AppLinkingScreen.test.tsx
- BrightID/src/components/HomeScreen.tsx
- BrightID/src/components/Tasks/TaskCard.tsx
- BrightID/src/components/Tasks/TasksScreen.test.tsx
- BrightID/src/components/Tasks/TasksSlice.ts
- BrightID/src/components/Tasks/UserTasks.ts
- BrightID/src/utils/verifications.ts
Query aura node for users `Aura` verification:
**Show aura verification badge on homescreen**
**Add an achievement for Aura verification:**
> Add Aura verification

- BrightID/src/components/Apps/AppLinkingScreen.test.tsx
- BrightID/src/components/Apps/AppLinkingScreen.tsx
- BrightID/src/components/Apps/appThunks.ts
- BrightID/src/components/Apps/model.ts
- BrightID/src/reducer/types.d.ts
- BrightID/src/utils/constants.ts
Before starting the link process perform the following checks:
- Is user meeting all verifications?
- v6: If there are already linked signatures, check if the same AppUserId is used
- v6: try to update blind signatures for the app, check if user is on a primary device
> Check verifications and signatures before trying to link

- BrightID/src/components/HomeScreen.tsx
> Add direct link to connection party when user has no verification

- BrightID/locales/en/translation.json
- BrightID/locales/fr/translation.json
> Fix: typos

- BrightID/android/build.gradle
- BrightID/scripts/zap.sh
This should fix building staging and release builds through github actions.
> Build tools 30

- BrightID/index.js
- BrightID/package.json
- BrightID/src/bootstrap.ts
- BrightID/src/components/SideMenu/LogFileScreen.tsx
- BrightID/src/components/SideMenu/SettingsScreen.tsx
- BrightID/src/utils/constants.ts
- BrightID/src/utils/logging.ts
- BrightID/yarn.lock
Add a new section "Access logfiles" to the Settings screen.
- A new logfile is created at every app startup
- Logfiles older than 3 days are deleted automatically at app startup
- All calls to console.log/warn/error are routed to the logfile
- In DEV mode logs are routed to console and logfile, in release mode only to logfile
- Log can be copied to clipboard
> Access app logs

- BrightID/e2e/connectionDetails.spec.ts
- BrightID/e2e/groupManagement.spec.ts
- BrightID/e2e/groups.spec.ts
- BrightID/e2e/importAccount.spec.ts
- BrightID/e2e/reportConnection.spec.ts
- BrightID/e2e/testUtils.ts
- BrightID/src/actions/apps.ts
- BrightID/src/actions/fetchUserInfo.ts
- BrightID/src/components/EditProfile/socialMediaThunks.ts
- BrightID/src/components/HomeScreen.tsx
- BrightID/src/routes/helpers.tsx
Fix a couple of bugs that could result in race conditions/crashes.
Fix detox end-2-end tests
> Fix fetch user info

- BrightID/src/components/Onboarding/RecoveryFlow/RecoveryCodeScreen.tsx
- BrightID/src/components/Onboarding/RecoveryFlow/useGenerateRecoveryQrAndPoll.ts
> refactor: create useGenerateRecoveryQrAndPoll hook for RecoveryCodeScreen

- BrightID/package.json
- BrightID/src/components/Onboarding/RecoveryFlow/RecoveringConnectionCard.tsx
> Fix bug in RecoveringConnectionCard.tsx introduced by #1202

- BrightID/src/components/Onboarding/RecoveryFlow/thunks/backupThunks.ts
- BrightID/src/components/Onboarding/RecoveryFlow/thunks/recoveryThunks.ts
Store hash of the data that is already in the backup service to avoid uploading the same data again
> feat: store hashes of backup data during fetchBackupData operation

- BrightID/android/build.gradle
Set targe API-Level to 35 as required by Google Play Store.
> bump target SDK version to 35
